name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install snowflake-connector-python

    - name: Deploy to Snowflake Dev Database
      env:
        SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SNOWFLAKE_DATABASE: ${{ secrets.SF_DEV_DATABASE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
      run: |
        python .github/workflows/deploy_to_snowflake.py

    - name: Install SnowSQL
      run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/scripts/installers/ubuntu18/snowflake-snowsql-linux_x86_64.bash
          bash snowflake-snowsql-linux_x86_64.bash --yes
  
    - name: Deploy to Snowflake
      env:
        SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
        SNOWFLAKE_DATABASE: ${{ secrets.SF_DEV_DATABASE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
        SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
      run: |
          python .github/workflows/invoke_snowsql.py    

    - name: Clean up
      run: |
        rm -rf ./*