name: Install SnowSQL

on:
  push:
    branches:
      - main

jobs:
  install_snowsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl file

      - name: Download SnowSQL
        run: curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-linux_x86_64

      - name: Verify Download
        run: file snowsql-linux_x86_64

      - name: Install SnowSQL
        run: |
          chmod +x snowsql-linux_x86_64
          ./snowsql-linux_x86_64 -n
          echo 'export PATH=$PATH:$HOME/bin' >> $GITHUB_ENV
          export PATH=$PATH:$HOME/bin

      - name: Verify SnowSQL Installation
        run: snowsql --version
