name: Install SnowSQL from test file

on:
  push:
    branches:
      - main

jobs:
  install_snowsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl file

      - name: Download SnowSQL
        run: |
          curl -o snowsql-linux_x86_64 https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-linux_x86_64
          file snowsql-linux_x86_64

      - name: Check for XML Download
        run: |
          if grep -q '<?xml version="1.0" encoding="UTF-8"?>' snowsql-linux_x86_64; then
            cat snowsql-linux_x86_64
            exit 1
          fi

      - name: Install SnowSQL
        run: |
          chmod +x snowsql-linux_x86_64
          ./snowsql-linux_x86_64 -n
          echo 'export PATH=$PATH:$HOME/bin' >> $GITHUB_ENV
          export PATH=$PATH:$HOME/bin

      - name: Verify SnowSQL Installation
        run: snowsql --version
