name: Install SnowSQL

on:
  push:
    branches:
      - main

jobs:
  install_snowsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Download SnowSQL
        run: |
          SNOWSQL_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.3.0-linux_x86_64.bash"
          curl -O $SNOWSQL_URL
          file snowsql-1.3.0-linux_x86_64.bash

      - name: Check for XML Download
        run: |
          if grep -q '<?xml version="1.0" encoding="UTF-8"?>' snowsql-1.3.0-linux_x86_64.bash; then
            echo "Error: Downloaded file is not the expected binary."
            cat snowsql-1.3.0-linux_x86_64.bash
            exit 1
          fi

      - name: Install SnowSQL
        run: |
          chmod +x snowsql-1.3.0-linux_x86_64.bash
          ./snowsql-1.3.0-linux_x86_64.bash -y
          echo 'export PATH=$PATH:$HOME/.snowsql/bin' >> $GITHUB_ENV
          export PATH=$PATH:$HOME/.snowsql/bin

      - name: Verify SnowSQL Installation
        run: snowsql --version
