name: Install SnowSQLaaaaaaaaaaaaaaaa

on:
  push:
    branches:
      - main

jobs:
  install_snowsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg

      - name: Download SnowSQL installer and signature
        run: |

            curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.0-linux_x86_64.bash
        
            chmod +x snowsql-1.3.0-linux_x86_64.bash
              
            ./snowsql-1.3.0-linux_x86_64.bash -y

      - name: Verify SnowSQL Installation
        run: snowsql --version
