name: Install and Configure SnowSQL for running the Deployment Script

on:
  push:
    branches:
      - main

jobs:
  install_snowsql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Download SnowSQL installer script
        run: curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.0-linux_x86_64.bash

      - name: Set execute permissions for installer script
        run: chmod +x snowsql-1.3.0-linux_x86_64.bash

      - name: Execute SnowSQL installer
        run: ./snowsql-1.3.0-linux_x86_64.bash -y > snowsql_install.log 2>&1

      - name: Check installation status
        run: |
          if [ $? -eq 0 ]; then
            echo "SnowSQL installed successfully."
          else
            echo "SnowSQL installation failed. Check snowsql_install.log for details."
          fi
